### ISSUE TITLE
Add doc about image conversion 

### ISSUE THREAD

**Issue by patrickelectric** [IBEXcps/HaLiO-sw#18]

**Comment by rafaellehmkuhl** [comment]
Will do it now

**Comment by rafaellehmkuhl** [comment]
Done!

# Converting images to insert on OLED screens

The first step is to create a image that you would like to put on the OLED screen.

Remeber that the screen is 128x64 pixels, an so should be your image.
Remember also that OLED screens are boolean screens (they don't have grayscale) so you should make your images Black & White.

Prefer to save your images in PNG, so the compression don't destroy your beautiful pixel-art.

Here is an example:

![halio_logo_128x64](https://user-images.githubusercontent.com/6551040/33668705-a9e70e56-da87-11e7-94f0-07cc1f0743e6.png)

The white pixeld will appear illuminated on the screen, while the black ones won't. If you would like to invert you B&W image, you can use [this site](http://pinetools.com/invert-image-colors).

When you have your image ready, you can use [this site](https://convertio.co/pt/jpg-xbm/) to convert your image to the XBM format.

Once your image is converted, download it and open with your prefered text editor. The image code should be something like this:

```
#define 2cd657c984814176dad46aa991443621_width 128
#define 2cd657c984814176dad46aa991443621_height 64
static char 2cd657c984814176dad46aa991443621_bits[] = {
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 

...
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x88, 0x00, 0x00, 
  0x00, 0x00, 0x00, 0x00, };
```

Notice that the image got named **2cd657c984814176dad46aa991443621**. You can change it freely to better adequate to your project. We will change it to **halio_logo** The final result should be something like this:

```
#define halio_logo_width 128
#define halio_logo_height 64
static char halio_logo_bits[] = {
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 

...
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x88, 0x00, 0x00, 
  0x00, 0x00, 0x00, 0x00, };
```

Where should we put it? Code or wiki?

**Comment by patrickelectric** [comment]
@rafaellehmkuhl Do you have power to edit the wiki ?

**Comment by rafaellehmkuhl** [comment]
Nope.

GIBE ME POWAR

**Comment by patrickelectric** [comment]
@rafaellehmkuhl Can you try now ?

**Comment by rafaellehmkuhl** [comment]
Still can't

**Comment by patrickelectric** [comment]
@rafaellehmkuhl YOU GOT THE POWAR

**Comment by rafaellehmkuhl** [comment]
much power
done
we can close
