### ISSUE TITLE
HalioCeption

### ISSUE THREAD

**Issue by rafaellehmkuhl** [IBEXcps/HaLiO-sw#30]
![halioception](https://user-images.githubusercontent.com/6551040/33666250-90c68ab6-da80-11e7-98c6-9be09cee089e.png)

I think we have a build problem rsrs

**Comment by rafaellehmkuhl** [comment]
@Williangalvani @patrickelectric

**Comment by patrickelectric** [comment]
What is that image ?
Try with the new PR that correct the build folder location.

**Comment by rafaellehmkuhl** [comment]
My build folder. It builds inside the builds.
Which PR is that?

**Comment by patrickelectric** [comment]
Sorry, it's already [in master](https://github.com/IBEXcps/HaLiO-sw/commit/3fe04df381674b72729274e337d9db8fb1906b4d).

Try to delete this build folder inside smartmeter, it's an old struct.
rebase your work or branch over master and run `make`, it should 
create a build folder in HaLiO-sw and not in smartmeter;

**Comment by rafaellehmkuhl** [comment]
Perfect

**Comment by rafaellehmkuhl** [comment]
I love painless rebases
